FROM jenkins/jenkins:lts-jdk17

# Switch to root user
USER root

# Install AWS CLI and Kubectl and Helm
RUN apt-get update && \
    apt-get install -y awscli && \
    apt-get install -y curl && \
    curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash  && \
    apt-get clean

# Switch back to the jenkins user
USER jenkins